---
title: "Creating Seasonal Curves in R"
author: "Will Simmons"
date: "9/28/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(here)
```


## Importing and viewing the data

```{r import_data}
seasonal = read_excel('./data/seasonal_data_tidy.xlsx')  # was this exported from MATLAB? pretty sure - since did fourier modeling there

area_names <- readRDS(here("data/area_names.rds"))
```

## Trying out some curves
Weʻll be drawing curves for Areas 5, 17, 11, 10, 7, 15

# Area 5
```{r area5_plot, dev='CairoPNG', fig.width = 9}
index_5 = seasonal$surv_area == 5

area5_plot =
seasonal[index_5,] %>% 
  ggplot(aes(x = daynum, y = fourier)) +
  geom_line(size = 1.7, color = "#BA2D0B", show.legend = FALSE) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#BA2D0B", alpha = 0.17, show.legend = FALSE) + # adding confidence limits
  
  ggtitle('Area 5: Chilmari/Kaunia') + 
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) + # centering title - put in code after main theme
  theme(panel.grid.minor = element_blank()) +
  
  # this code sets the axis bounds and removes unnecessary space around plot
  scale_x_continuous(
    breaks = c(1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336), 
    labels = c('J','F','M','A','M','J','J','A','S','O','N','D'),
    limits = c(0.5, 366.5), 
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(-1.35, -0.65), expand = c(0, 0)) +
  
  ylab('Mean Weight-for-Length Z-score') +
  xlab(NULL)

area5_plot

ggsave("area5_seasonal.pdf",
       area5_plot,
       path = here("output"),
       width = 6,
       height = 4)

ggsave("area5_seasonal.png",
       area5_plot,
       path = here("output"),
       width = 6,
       height = 4,
       dpi = 300)
```

# Area 17
```{r area17_plot, dev='CairoPNG', fig.width = 9}
index_17 = seasonal$surv_area == 17

area17_plot =
seasonal[index_17,] %>% 
  ggplot(aes(x = daynum, y = fourier)) +
  geom_line(size = 1.7, color = "#73BA9B", show.legend = FALSE) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#73BA9B", alpha = 0.2, show.legend = FALSE) + # adding confidence limits
  
  ggtitle('Area 17: Golapganj/Fenchuganj') + 
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) + # centering title - put in code after main theme
  theme(panel.grid.minor = element_blank()) +
  
  # this code sets the axis bounds and removes unnecessary space around plot
  scale_x_continuous(
    breaks = c(1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336), 
    labels = c('J','F','M','A','M','J','J','A','S','O','N','D'),
    limits = c(0.5, 366.5), 
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(-1.35, -0.65), expand = c(0, 0)) +
  
  ylab('Mean Weight-for-Length Z-score') +
  xlab(NULL)

area17_plot

ggsave("area17_seasonal.pdf",
       area17_plot,
       width = 6,
       height = 4)

ggsave("area17_seasonal.png",
       area17_plot,
       width = 6,
       height = 4,
       dpi = 300)
```

# Area 11
```{r area11_plot, dev='CairoPNG', fig.width = 9}
index_11 = seasonal$surv_area == 11

area11_plot =
seasonal[index_11,] %>% 
  ggplot(aes(x = daynum, y = fourier)) +
  geom_line(size = 1.7, color = "#01110A", show.legend = FALSE) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#01110A", alpha = 0.2, show.legend = FALSE) + # adding confidence limits
  
  ggtitle("Area 11: Moheshkhali/Cox's Bazaar") + 
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) + # centering title - put in code after main theme
  theme(panel.grid.minor = element_blank()) +
  
  # this code sets the axis bounds and removes unnecessary space around plot
  scale_x_continuous(
    breaks = c(1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336), 
    labels = c('J','F','M','A','M','J','J','A','S','O','N','D'),
    limits = c(0.5, 366.5), 
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(-1.35, -0.65), expand = c(0, 0)) +
  
  ylab('Mean Weight-for-Length Z-score') +
  xlab(NULL)

area11_plot

ggsave("area11_seasonal.pdf",
       area11_plot,
       width = 6,
       height = 4)

ggsave("area11_seasonal.png",
       area11_plot,
       width = 6,
       height = 4,
       dpi = 300)
```


# Area 10
```{r area10_plot, dev='CairoPNG', fig.width = 9}
index_10 = seasonal$surv_area == 10

area10_plot =
seasonal[index_10,] %>% 
  ggplot(aes(x = daynum, y = fourier)) +
  geom_line(size = 1.7, color = "#0EB1D2", show.legend = FALSE) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#0EB1D2", alpha = 0.2, show.legend = FALSE) + # adding confidence limits
  
  ggtitle("Area 10: Mirzaganj/Patuakhali Sadar") + 
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) + # centering title - put in code after main theme
  theme(panel.grid.minor = element_blank()) +
  
  # this code sets the axis bounds and removes unnecessary space around plot
  scale_x_continuous(
    breaks = c(1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336), 
    labels = c('J','F','M','A','M','J','J','A','S','O','N','D'),
    limits = c(0.5, 366.5), 
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(-1.35, -0.65), expand = c(0, 0)) +
  
  ylab('Mean Weight-for-Length Z-score') +
  xlab(NULL)

area10_plot

ggsave("area10_seasonal.pdf",
       area10_plot,
       width = 6,
       height = 4)

ggsave("area10_seasonal.png",
       area10_plot,
       width = 6,
       height = 4,
       dpi = 300)
```


# Area 7
```{r area7_plot, dev='CairoPNG', fig.width = 9}
index_7 = seasonal$surv_area == 7

area7_plot =
seasonal[index_7,] %>% 
  ggplot(aes(x = daynum, y = fourier)) +
  geom_line(size = 1.7, color = "#E2C290", show.legend = FALSE) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#E2C290", alpha = 0.2, show.legend = FALSE) + # adding confidence limits
  
  ggtitle("Area 7: Shakhipur/Sreepur") + 
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) + # centering title - put in code after main theme
  theme(panel.grid.minor = element_blank()) +
  
  # this code sets the axis bounds and removes unnecessary space around plot
  scale_x_continuous(
    breaks = c(1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336), 
    labels = c('J','F','M','A','M','J','J','A','S','O','N','D'),
    limits = c(0.5, 366.5), 
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(-1.35, -0.65), expand = c(0, 0)) +
  
  ylab('Mean Weight-for-Length Z-score') +
  xlab(NULL)

area7_plot

ggsave("area7_seasonal.pdf",
       area7_plot,
       width = 6,
       height = 4)

ggsave("area7_seasonal.png",
       area7_plot,
       width = 6,
       height = 4,
       dpi = 300)
```

# Area 15
```{r area15_plot, dev='CairoPNG', fig.width = 9}
index_15 = seasonal$surv_area == 15

area15_plot =
seasonal[index_15,] %>% 
  ggplot(aes(x = daynum, y = fourier)) +
  geom_line(size = 1.7, color = "#748CAB", show.legend = FALSE) +
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#748CAB", alpha = 0.2, show.legend = FALSE) + # adding confidence limits
  
  ggtitle("Area 15: Daulatpur/Gangni") + 
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) + # centering title - put in code after main theme
  theme(panel.grid.minor = element_blank()) +
  
  # this code sets the axis bounds and removes unnecessary space around plot
  scale_x_continuous(
    breaks = c(1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336), 
    labels = c('J','F','M','A','M','J','J','A','S','O','N','D'),
    limits = c(0.5, 366.5), 
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(-1.35, -0.65), expand = c(0, 0)) +
  
  ylab('Mean Weight-for-Length Z-score') +
  xlab(NULL)

area15_plot

ggsave("area15_seasonal.pdf",
       area15_plot,
       width = 6,
       height = 4)

ggsave("area15_seasonal.png",
       area15_plot,
       width = 6,
       height = 4,
       dpi = 300)
```

<!-- Making a function... -->

```{r, include = F}

seasonal_plot <- function(area,
                          col = wesanderson::wes_palettes[[sample(1:19, 1)]][[sample(1:4, 1)]])  # random color

{
  
  seasonal <- read_excel('./data/seasonal_data_tidy.xlsx')  # was this exported from MATLAB? pretty sure - since did fourier modeling there
  
  area_names <- readRDS(here("data/area_names.rds"))
  
  area_ind <- seasonal$surv_area == area
  
  p <- 
    seasonal[area_ind,] %>% 
    ggplot(aes(x = daynum, y = fourier)) +
    geom_line(size = 1.7, color = col, show.legend = FALSE) +
    geom_ribbon(
      aes(ymin = lower, ymax = upper),
      fill = col,
      alpha = 0.2,
      show.legend = FALSE
    ) +
    ggtitle(area_names[[area,2]]) + 
    theme_light() +
    theme(
      plot.title = element_text(hjust = 0.5),
      panel.grid.minor = element_blank()
    ) +
    scale_x_continuous(
      breaks = c(1, 32, 61, 92, 122, 153, 183, 214, 245, 275, 306, 336),
      labels = c('J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'),
      limits = c(0.5, 366.5),
      expand = c(0, 0)
    ) +
    scale_y_continuous(limits = c(-1.4, -0.55), expand = c(0, 0)) +
    ylab('Mean Weight-for-Length Z-score') +
    xlab(NULL)  
  
  p
  
}

seasonal_plot(area = 4)

```

